services:
  - type: web
    name: http-server
    env: {}
    build_command: docker build -t my-http-server .
    start_command: docker run -p 8000:8000 -e RCLONE_CONFIG="<Paste your rclone.conf content here>" my-http-server
